* TODO This meeting, Tuesday November 18th
- Things we have yet to design
  - Driver program to the script based one.
  - Parser
  - Glue between parser, and internal represenatation of cards
    - This is the thing that takes the parsed script from the parser, and assembles the layouts and cards and decals from it.
    - The parser may very well make a good amount of these, decals would make sense. Or not.
- Examples ( Need 2, want 3, maybe 4)
  - Finish up 52 playing card example
  - do monopoly
  - Do Pokemon
  - Do settlers of Catan
- Layout classes for parser
- Elaborate on existing uml
- Could potentially break into parts, composite, renderer, etc
  - Need to describe the renderer, currently is absent
  - Need composite operations, Layout composite will probably want a .render(family,relativeposition, size).
  - Decals
    - String decal needs a font when created, image decal needs image, etc. All these constructors and such need to be formally done.
  - Multiple UML diagrams.
    - One for the parser, one for the composite, one for the decals...
  - Write user manual, describing what a Layout, Family, etc are.
      
** DONE 
- Choose a basic design + language so we can start working!
- Finalize scripting language


* Tentative Schedule
- Friday : Finalized Design, overall uml done or nearly done, side umls mostly done.
- Monday : Everything except per class docs done
- Over Thanksgiving break : We break up the classes, and assign each person an even amount of classes to right specs on
- Turn in

 
* THE TODO Before Thanksgiving 
- Rework examples a tiny bit, family needs a name
- Builder Construction
  - Make the builders
  - Make the ScriptObject subclasses more detailed
- Parser : Mostly done, should probably mention a tiny bit about how it will recur to work...
